pipeline:
  name: test-vagrant
  identifier: testvagrant
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: vagrant
        build: <+input>
  stages:
    - stage:
        name: backport
        identifier: backport
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Backport changes to stable-website
                  identifier: Backport_changes_to_stablewebsite
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorpdev/backport-assistant:0.2.3
                    shell: Sh
                    command: backport-assistant backport -automerge
