pipeline:
  name: test-vagrant
  identifier: testvagrant
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: builds
        identifier: builds
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Code Checkout
                  identifier: Code_Checkout
                  spec:
                    connectorRef: account.harnessImage
                    image: actions/checkout@v1
                    shell: Sh
                    command: echo "suuccessfull"
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: vagrant
        build: <+input>
